### ISSUE TITLE
Create Diagram

### ISSUE THREAD

**Issue by JaimeGonz** [BrightCoders-Institute/proyecto-final-rn-teama#31]
```[tasklist]
### Tasks
- [ ] UML flow diagram
```

**Comment by ecruz17** [comment]
https://www.figma.com/file/qWosALcBBfTPlPTpRFYGS7/proyecto-final?type=design&node-id=226-372&mode=design&t=JGloajv6qfu8JcMP-0

![imagen](https://github.com/BrightCoders-Institute/proyecto-final-rn-teama/assets/47923715/7b368329-9cf7-4746-a6f7-0c5778f7c5fa)
